version: "3.7"

services:
  soccer_database:
    image: postgres
    container_name: soccer_database
    restart: always
    environment:
      POSTGRES_USER: soccer
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: soccer
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    network_mode: host
  app:
    build: .
    container_name: soccer
    environment:
      - DATABASE_URL=postgres://soccer_deploy_pg_user:LC70rMa8WKIyta7K6VM8fe1KXfesybOy@dpg-cgkcar8rddleudu2kq2g-a/soccer_deploy_pg
      - DATABASE_TEST_URL=postgresql://root:123456@localhost:5432/test?schema=publi
    volumes:
      - .:/usr/app
    network_mode: host
